name: 'l5test'
version: '1.0.0'
config-version: 2

profile: 'l5test'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  l5test:
    +materialized: table

seeds:
  database: "{{ target.database }}"
  quote_columns: false
